---
title: Software for management of knowledge organization systems
authors:
- name: Jakob Voß
  orcid: 0000-0002-7613-4123
  affiliations:
   - name: Verbundzentrale des GBV (VZG)
bibliography: references.bib
date: last-modified
url: "https://bartoc.org/software"
---

::: {.content-visible when-format="pdf"}
\large
*This report is much more usable in HTML at <https://bartoc.org/software>!*
\vspace*{20mm}
:::

The terminology registry **[BARTOC](https://bartoc.org/)** collects information about all kinds of **knowledge organization systems** (KOS) such as controlled vocabularies, classifications, ontologies, and other semantic artifacts. This report summarizes information about [software for KOS management](#kos-software).

## Scope

This report is limited to **[specialized KOS software](#kos-software) for editing, vizualizing and/or analyzing terminologies.** The term "terminology" in this document is used as synonym for all kinds of KOS. Software is excluded if:

- it is not aimed at KOS management in particular but [more generic software] such as database management systems, content management systems and text editors,
- it is [more specific software], restricted to a limited type of KOS, such software for linguistic terminology management and identifier systems,
- it [cannot be used](#limited-use) as stand-alone application, like programming libraries, and hosted services.

Software for **ontology alignment** is only included if it is more then a research prototype and if we managed to get it running. See @Bergman2018 for a comprehensive list of software in this category. The [Ontology Alignment Evaluation Initiative (OAEI)](https://oaei.ontologymatching.org/) motivates the creation of tools for automated ontology alignment.

<!-- start landscape mode in PDF -->
\newpage
\KOMAoptions{paper=landscape,pagesize,DIV=20}
\recalctypearea

## KOS software

```{python}
import pandas as pd
kos = pd.read_json('kos-software.json')
```

This report includes **`{python} len(kos.index)`** instances of KOS software so far. The list is managed [in a JSON file](kos-software.json) as array of [CodeMeta](https://codemeta.github.io/) records with fields as [described below](#metadata). Applications without license or repository are closed source. Deprecated applications are included for historical reference.

```{python}
#| label: tbl-software
from IPython.display import Markdown
from tabulate import tabulate
from urllib.parse import urlparse
from IPython.display import display, HTML
import re

def hyperlink(row):
    if pd.notna(row['url']):
        return f'<a href="{row["url"]}">{row["name"]}</a>'
    else:
        return row['name']    

def cell(value):
    if isinstance(value, bool):
        return "✓" if value else "-"
    if isinstance(value, str) and value.startswith("https://spdx.org/licenses/"):
        license_name = value.replace("https://spdx.org/licenses/", "").split("-")[0]
        return f'<a href="{value}">{license_name}</a>'
    elif type(value) is str and re.match(r"^https?://",value):
        url = urlparse(value)
        host = url.hostname.split(".")[-2]
        return f'<a href="{value}">{host}</a>'
    elif isinstance(value, list):
        return ", ".join(str(item) for item in value)
    elif not pd.notna(value):
        return ""
    elif type(value) is float: # pd converts string to float
        return int(value)
    return value

kos["name"] = kos.apply(hyperlink, axis=1)
kos = kos.sort_values(by=["dateModified"],ascending=False)
kos["category"] = kos.apply(lambda row: [c[7:] for c in (row["applicationCategory"] or [])] + (row["applicationSubCategory"] or []),axis=1)
kos = kos.drop(columns=["url", "applicationCategory", "applicationSubCategory"])
kos = kos.applymap(cell)
kos = kos.rename(columns={"operatingSystem":"system","programmingLanguage":"languages","codeRepository":"repository","dateModified":"update","applicationSubCategory":"category"})
display(HTML(kos.to_html(escape=False,index=False)))
```

Please [open an issue](https://github.com/gbv/bartoc-vocabulary-software/issues) if some relevant software is missing or data seems invalid!

<!-- end landscape mode in PDF -->
\newpage
\KOMAoptions{paper=portrait,pagesize,DIV=10}
\recalctypearea

## Metadata

Machine-readable description of the software is based on [CodeMeta](https://codemeta.github.io/) plus custom fields `api` and `edit`.

Field | Purpose 
------|--------
`name` | name of the software
`url` | Homepage URL
`operatingSystem` | operating system or similar dependency (Web, CLI...)
`api` | whether a web service or similar API is provided to connect to
`edit` | whether vocabularies can be modified with the software
`programmingLanguage` | programming language(s) from SPDX
`license` | license of the software (if free software)
`codeRepository` | source Code repository (if open source)
`dateModified` | year of most recent update
`applicationCategory` | generic type of software
`applicationSubCategory` | type of KOS software

: {tbl-colwidths="[25,75]"}

The metadata is also [made available in RDF](kos-software.ttl).

## KOS software categories

```{python}
df = pd.read_json('kos-software.json')
categories = {}
for item in df["applicationSubCategory"]:
    for category in item:
        if category in categories:
            categories[category] += 1
        else:
            categories[category] = 1
```

- **viewer**: to display terminologies (`{python} categories['viewer']`)
- **editor**: to create and modify terminologies (`{python} categories['editor']`)
- **mapping editor**: to create and modify mappings/alignments (`{python} categories['mapping editor']`)
- **converter**: to convert from one format into another (`{python} categories['converter']`)
- **validator**: to check terminologies (`{python} categories['validator']`)
- **database**: to store terminologies (`{python} categories['database']`)

## Related software

Knowledge organization systems can also be managed with other types software [excluded from this report](#scope).

### More generic software

Simple terminologies can be managed in a **spreadsheet** (LibreOffice Calc, Excel, Google Sheets...). This software lacks most special functionality for terminology management but the usability and accessibility is very high. Some tools in the list above (VocExcel, voc4cat-tool) enhance standard spreadsheets with terminology management functionalities.

The same applies to **database management systems** (RDBMS, NoSQL, RDF triple stores, property graph databases...) with some additional features such as unique key constraints but less usability. An edge case might be systems for management of knowledge graphs (such as Wikibase), included above.

Tools for personal **knowledge management** (such as [Obsidian] and [Notion]) help to structure ideas and concepts. Similar tools exist for enterprises to support data integration, knowledge management and/or business intelligence of an organization (for instance [PoolParty Semantic Suite]).

Several **Content Management Systems** (CMS) allow to manage a list or hierarchy of topics or other entities for knowledge managements. If these lists can be exported, the CMS can be applied to manage terminologies. An example is [Drupal], which was used for the first version of BARTOC terminology registry.

Terminologies can also directly be managed in **files** for instance in RDF/Turtle syntax. This only requires a **text editor** but the risk is high to introduce errors. A **version control system** such as git can be used on top to track changes.

### More specific software

The term **terminology management** is also used for systems to organize the terms, definitions, and translations used in an organization. See @Montoro2018 for a list of terminology management systems. The focus of these systems is more on translation but there is some overlap with KOS management. Software aimed at simple lists of terms, definitions, glossaries and similar is also excluded from this report.

Several systems and applications exist to manage identifiers (Domain Name System, [w3id](https://w3id.org/)...). These **identifier systems** are relevant to manage KOS but they are rarely enough for KOS management alone. See [Bioregistry](https://bioregistry.io/) for a registry of identifier systems used with KOS.

Several tools, frameworks and programming languages exist for **data transformation** between different formats and/or models ([XSLT], [jq], [Catmandu], [DTL], [LinkML-map], [QVT]...). These transformations often imply or make use of terminology mappings.

Some tools for **data curation** also make use of or require terminologies, for instance [OpenRefine] and [mix'n'match]. The latter comes close to a mapping editor but it is limited to mappings with Wikidata.

### Limited use

Some organizations run **hosted services** for KOS management or related services. Examples include [DANTE](https://doi.org/10.11588/akmb.2018.1.63475), [xTree](https://xtree-public.digicult-verbund.de/) and [Linked Open Vocabularies (LOV)](http://lov.okfn.org/dataset/lov/). More examples may be found in the BARTOC [list of terminology registries](https://bartoc.org/registries).

**programming libraries** such as [cocoda-sdk], [TSS Widgets], [jskos-vue], [SeMRA], and [ng-skos] are used to build KOS software.

### Other software

The following do not fit into the software categories above or there was not enough information:

- [Scripts to analyze concept drift](https://github.com/Multilingual-LGBTQIA-Vocabularies/Examing_LGBTQ_Concepts) as part of a research project (Open Source)
- [TopBraid EDG](https://www.topquadrant.com/topbraid-edg/) is a commercial knowledge graph editor
- [Apelon DTS](https://www.apelondts.org/) (Distributed Terminology System) and Apelon TermManager are commercial terminology editors. An earlier [version from 2013](https://apelon-dts.sourceforge.net/) is available as Open Source.
- [Grafo](https://gra.fo/) is a collaborative knowledge graph editor, available as commercial web application
- [Vitro](https://github.com/vivo-project/Vitro) is a framework for semantic web applications, used in [VIVO](https://vivoweb.org/)

## Related works

This report is based on two reports [@Voss2016a;@Voss2016b] from the beginning of [project coli-conc](https://coli-conc.gbv.de/) that led to a [a wiki page](https://github.com/gbv/bartoc.org/wiki/Software-for-controlled-vocabularies) managed between 2020 and 2024. See also @Miles2009 for a report created during the specification of SKOS W3C Recommendation, the corresponding wiki pages at <https://www.w3.org/2001/sw/wiki/Category:Editor>, and @Bergman2018 for a list of software for ontology alignment.

## Acknowledgements

Contributions to this report or to its predecessors have been provided by 
Adrian Pohl,
Antoine Isaac,
David Linke,
Eugene Morozov,
Koen Van Daele,
Matthias Löbe,
Monty Bitto,
Roman Baum,
Susanne Arndt,
and possibly others.

## References

:::{#refs}
:::

[Drupal]: https://www.drupal.org/
[OpenRefine]: https://openrefine.org/
[mix'n'match]: https://mix-n-match.toolforge.org/
[Obsidian]: https://obsidian.md/
[Notion]: https://www.notion.com/
[TSS Widgets]: https://github.com/ts4nfdi/terminology-service-suite
[jskos-vue]: https://github.com/gbv/jskos-vue/
[ng-skos]: http://gbv.github.io/ng-skos/
[cocoda-sdk]: https://github.com/gbv/cocoda-sdk/
[PoolParty Semantic Suite]: https://www.poolparty.biz/product-overview
[Catmandu]: https://librecat.org/
[jq]: https://jqlang.org/
[XSLT]: https://en.wikipedia.org/wiki/XSLT
[LinkML-map]: https://linkml.io/linkml-map/
[QVT]: https://en.wikipedia.org/wiki/QVT
[DTL]: https://getdtl.org/
[SeMRA]: https://semra.readthedocs.io/
